### ISSUE TITLE
travis-ci docs updates

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/support-firecloud#100]
Very good docs, @andreineculau! Make me want to contribute :) 

I will submit a PR with updates later on, here are the issues I found. Please, review and let me know if my assumptions are correct, so I will proceed with PR.

1. The very first step to setup integration should be to go to https://github.com/organizations/tobiipro/settings/installations, press `Configure` on Travis CI and give it access to the new repo in `Repository access` dropdown.
1. `enable Build only if .travis.yml is present` does not seem to be there anymore, so can be removed, I guess.
1. Do we need to add `TRANSCRYPT_PASSWORD` as Travis-encrypted variable or use Travis web-UI? In the current docs, it says the first one, but apparently, it's not a requirement anymore.
1. Clarify the `deploy` section. Apparently, one has to do `travis encrypt "<GH_TOKEN>"` and it to `deploy -> api_key`. Or no?
1. (ADDED) Migrate env vars
1. (ADDED) Replace default SSH key

**Comment by andreineculau** [comment]
1. 👍 
2. 👍 
3. webui, the "requirement" has shifted to having only webui vars (both easier process and more convenient for changes)
4. deploy: if you can copy the deploy section from another repo, then yes `travis encrypt "<GH_TOKEN>" -> api_key` AND change the condition to match the repo's name

THANKS!

Note2self: also document how to migrate other env vars from an already-integrated repo

**Comment by IanSavchenko** [comment]
> Note2self: also document how to migrate other env vars from an already-integrated repo

can do that too. Strangely, `printenv` didn't print properly everything for me, looked like the output was cut off from the top, so not all the variables were visible. In the end, had to echo every secret variable, but suspecting that `printenv <variables list>` should also do.

One more thing to mention: replace SSH key with `tobiiprotools`.

**Comment by andreineculau** [comment]
I do `printenv | grep DEV_`, etc

Yes, key too!
