### ISSUE TITLE
Reenable termination protection for PROD stacks

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/support-firecloud#106]

**Comment by IanSavchenko** [comment]
Why did you decide not to have it in support-firecloud?

**Comment by andreineculau** [comment]
The check itself is specific (ENV_NAME is prod).
The only thing i could do towards having the aws-cli call in one place is to define the make function here and let the check happen in each .inc.mk file

Or am i missing smth obvious?!

**Comment by IanSavchenko** [comment]
No, nothing obvious :) 
But it seems to me like a very repetitive pattern. You could check `PROD_NS` from `CONST.inc`. For `atex-platform` it is `PROD_NS=prod,prod-staging`. I guess it's fine to enable termination protection for staging too.
