### ISSUE TITLE
Remove Ian Savchenko

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/support-firecloud#124]
Further actions must be done by another team members.

- [x] Remove from the [list of Auth0 admins](https://manage.auth0.com/dashboard/eu/tobiicloud/tenant/admins).

- [x] Remove on [DataDog](https://app.datadoghq.com/account/team). Probably, only @alsmyr can do this.

- [x] When `awsatex-devprod` infra stack is deployed, remove user in [AWS console](https://console.aws.amazon.com/iam/home?region=eu-west-1#/users/) in `atexdev` account.

- [x] ~Remove from repos with `transcrypt` and updated `transcrypt` passwords.~
  EDIT: Too extreme. Cutting off access to the repos is good enough. Changing all passwords every single time a team member leaves is unsustainable. And deleting the encrypted password in each repo will happen in time. /Andrei

- [x] ~Update all secrets in the `secrets` repo.~
  EDIT: Too extreme. Cutting off access to the repos is good enough. Changing all passwords every single time a team member leaves is unsustainable. /Andrei

**Comment by andreineculau** [comment]
THANKS, Ian!

Will have a look at offboarding doc next week. I've checked what I could on this ticket, datadog as you say is on @alsmyr 

Au revoir [Simone](https://www.youtube.com/watch?v=kwvvlTKi5cE) 👋
