### ISSUE TITLE
'make release' creates empty git stash which is not removed

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/support-firecloud#18]
Reproduced couple times on `eslint-config-firecloud`, I think.

**Comment by andreineculau** [comment]
"empty git stash" as in your repo is squicky clean, you get a "stash which is empty", it goes forward with the release, and then fails to pop the last (empty) stash?

do I read you correctly?

**Comment by IanSavchenko** [comment]
Yes. I didn't see any actual fail, but then stash "WIP..." keeps hanging.
