### ISSUE TITLE
unstable builds on macos

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/support-firecloud#191]
around 1 in 2 builds (I triggered around 50 in the last 2 weeks) on MacOS on Travis CI seem to fail with

```
08:19:31 [INFO] CALLING: ci/brew-util.inc.sh
107508:19:32 [INFO] CALLING: brew_update
107608:19:33 [INFO] brew_update(): Update...this will take a while...
1077fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining
1078Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
1079==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
1080  https://github.com/Homebrew/brew#donations
108108:24:50 [ERR ] ERROR: Failed brew update.
```

This seems to be an issue on Travis CI, no doubt, but is it really needed to call `brew update`?
For the sake of stable builds (i.e. as atomic as possible) with no unwanted upgrades but also with less failuring side-effects like this one, one solution is to **not** update repositories at all when skipping common dependencies (which translates to: when running inside a support-firecloud docker image).

See a possible implementation in https://github.com/rokmoln/support-firecloud/pull/197/files

**Comment by andreineculau** [comment]
One consequence is also faster builds since the update of the repositories can take even 5+ minutes.

**Comment by andreineculau** [comment]
just FYI the root cause for the high rate of failures seems to be on the github side, not travis: https://github.com/Homebrew/homebrew-core/issues/61772

**Comment by mahshidii** [comment]
We will move to Github action
