### ISSUE TITLE
revert to make test: check first ?

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/support-firecloud#20]
https://github.com/tobiipro/support-firecloud/commit/7ae01d34bbd48abff7589088e5905dc9c40c3192

@IanSavchenko there's one negative side-effect: running `make all test` now runs `check` twice. 

Before the 2nd one would have been swallowed due to `make`'s dependency graph.

Possible ways to go forward:

* leave as is, runs twice in one situation
* find a `make` trick to swallow the 2nd run
* revert
* don't run `check` as part of `test`
* ?

**Comment by andreineculau** [comment]
> find a make trick to swallow the 2nd run

now on master branch, but leaving this open as it's worth a short discussion

**Comment by IanSavchenko** [comment]
Let's quickly discuss in the office. All the options are more or less acceptable.

**Comment by IanSavchenko** [comment]
Decided to have target `just-test` without `check` run. There will be also `just-build` for consistency and because it's not handy to see `really-long-name-for-build` in error logs. We are trusting ourselves to not misuse `just-` targets.

**Comment by IanSavchenko** [comment]
Keeping it simple: no dependency on `check` for `build` and `test` targets.
