### ISSUE TITLE
"make release" should fail early if local repo is not up-to-date

### ISSUE THREAD

**Issue by tobiiasl** [tobiipro/support-firecloud#26]
Even when "make release" fails due to  local repo not up-to-date it will still trigger two builds (master and the "version tag" build).

It would be better if it failed early before updating version and stuff.

`~/gs-client$ make release
Makefile:142: warning: overriding recipe for target 'build-ts'
support-firecloud/repo/mk/js.build.ts.mk:19: warning: ignoring old recipe for target 'build-ts'
make: Entering directory '/Users/tobiaslindgren/git/firecloud/gs-client'
[DO  ] Release new patch version...
make[1]: Entering directory '/Users/tobiaslindgren/git/firecloud/gs-client'
Makefile:142: warning: overriding recipe for target 'build-ts'
support-firecloud/repo/mk/js.build.ts.mk:19: warning: ignoring old recipe for target 'build-ts'
[DO  ] Bumping patch version...
v0.0.14
[DONE]

[DO  ] Publishing version...
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 2.14 KiB | 1.07 MiB/s, done.
Total 7 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 3 local objects.
To github.com:tobiipro/gs-client.git
 * [new tag]           v0.0.14 -> v0.0.14
[DONE]

make[1]: Leaving directory '/Users/tobiaslindgren/git/firecloud/gs-client'
To github.com:tobiipro/gs-client.git
 ! [rejected]          master -> master (fetch first)
error: failed to push some refs to 'git@github.com:tobiipro/gs-client.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
make: *** [support-firecloud/repo/mk/js.publish.tag.mk:24: release/patch] Error 1
make: Leaving directory '/Users/tobiaslindgren/git/firecloud/gs-client'`

**Comment by andreineculau** [comment]
closing in favour of #28
