### ISSUE TITLE
move public repos to travis-ci.com ?

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/support-firecloud#36]
Travis CI seems to have an ongoing unification effort for public and private repos

Received this by mail https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

**Comment by alsmyr** [comment]
I think it's a good idea to be on one

**Comment by alsmyr** [comment]
I suppose the build history is lost with moving over but I see no issue with that. Do you?

**Comment by andreineculau** [comment]
ongoing. sent an email to travis

**Comment by IanSavchenko** [comment]
Earlier I set up a new integration between GH and Travis and Travis were supposed to migrate `.org` repos to `.com` some time during autumn automatically. I guess it didn't happen (:

**Comment by andreineculau** [comment]
should be done-done. some noise on the slack channels might follow saying the travis-ci.com build is now green (the builds have no history, so status changed from unknown to green)
