### ISSUE TITLE
util to upload CI/CD logs to a git reference

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/support-firecloud#49]
it is more extreme with Travis, where we have a limit of 4MB stdout/stderr log, but in general we may want to log some files for post-analysis of a CI/CD event

what we need is a small util that given a FOLDER and given a dynamic hidden REFERENCE, this util can be added to `travis.yml` in the `after_script` or `after_failure` section in order to `git add <FOLDER>; git commit -m "logs"` and `git push` to the reference (orphan or with the CI/CD checkout as parent commit).

dynamic hidden reference =
* dynamic: it should support taking the BUILD_ID env var for example, or the branch/tag that travis checked out
* hidden: because it shouldn't be a branch/tag or else it would pollute the repo for everyone e.g. `refs/logs/${BUILD_ID}`

**Comment by IanSavchenko** [comment]
Looks like some stupid limitation of Travis which requires a dirty hack :( 
Maybe it's better to push it to some (semi-public) S3 bucket with guid? So no one can guess the filename but the link will be printed in Travis log.

**Comment by andreineculau** [comment]
no, this is not so tightly related to Travis. Example: it doesn't make sense to print out the generated cloudformation templates, but you might want to have access to them regardless of the provisioning succeeding or failing

and if you're saying that hidden refs are hacks, they are not. all sorts of system use them. even github has the `refs/pulls` namespace for instance

about s3 - that's what you (read I) immediately think of. "I need to store my files somewhere. Where can i find a file/object storage?"

1. yet the CI/CD already has access to the repo (in many cases RW access, not just RO, because you might already need to push tags etc), and you already have defined who has access to travis/repo,

2. while S3 needs extra setup (new tokens to be stored secretly, bucket, bucket policies), and also separate permissions in terms of who in the team can access the logs (I definitely do not want those permissions to be broader than who can access travis or the repo)

PS: the only thing that I saw as an advantage is that on S3 you can set expiry rules. Though that's nothing that can't be done for git refs

**Comment by andreineculau** [comment]
It turns out that TravisCI should actually upload artifacts also on failure, just that the docs were out-of-sync. After contacting their support, there's a new PR to fix the docs https://github.com/travis-ci/docs-travis-ci-com/pull/2219 \o/

What this means is that we *could* have
* travis.yml with artifacts uploading to S3
* the S3 bucket could have short expiration times where
  * "anyone can write, but only a few authenticated users can read"
  * or "anyone can write *and read*, but only a few authenticated users can *list*" so that if you have access to the travis log, you could also click a link in the travis log and read the contents of the artifacts, but you wouldn't be able to query the S3 bucket and list all of the logs

What's nice with S3 is the short-expiry IMHO. UI wise it would be nicer to browse the logs on github.

**Comment by andreineculau** [comment]
closed via #75
