### ISSUE TITLE
should a Brewfile.inc.sh be made mandatory

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/support-firecloud#54]
I made a change in https://github.com/tobiipro/support-firecloud/commit/53e1cbf
but it's optional now, and I'm thinking it's simpler to always require a Brewfile.inc.sh

* which can reference specific bootstraps e.g. `source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-install-aws.inc.sh`
* or convenience bootstraps e.g. `source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-install-common.inc.sh`
* or just install specific brew packages e.g. `brew_install tensorflow`

I see it as a small breaking change FTW
wdyt @IanSavchenko ?

**Comment by IanSavchenko** [comment]
I don't think I'm following it here completely, so let's take it in the office.

**Comment by andreineculau** [comment]
We take it in the office, but just some numbers and context before then

Most repos were running on travis in containers (`sudo: false`) and because of limited permissions I only bothered with installing latest versions of bash, make and jq, basically saying: if you want a fast travis run (in constainers), then you're limited in what you have available.

Now, with removing `sudo:false` (Travis will run everything in VMs; no containers), everything went on the full-bootstrap flow of installing so much more than just bash, make and jq, thus taking **many minutes** before doing something simple and fast like "npm install, babelify, lint and run jest".

Having a `Brewfile.inc.sh` in the root of the repo makes it possible to dictate what you actually need for this repo, rather than install everything that we find as a good solid baseline.

In https://github.com/tobiipro/lodash-firecloud/pull/8 switching from the default `ci/brew-install-common.inc.sh` [which runs if there is no `Brewfile.inc.sh`](https://github.com/tobiipro/support-firecloud/blob/53e1cbf4850588573794e8ab9654ca40779ccbed/ci/linux/bootstrap#L17) to just `ci/brew-install-minimal.inc.sh` (minimal is actually the equivalent of what we were installing in previous container mode, just bash, make and jq) via `Brewfile.inc.sh` will cut the build time by around 400 seconds.

What I'm suggesting is to remove the fallback to `ci/brew-install-common.inc.sh` in support-firecloud, thus requiring a `Brewfile.inc.sh` file in each repo.
