### ISSUE TITLE
implement `npm audit` in repo/mk

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/support-firecloud#55]
`npm audit --json` or `npm audit --parseable` actually

don't know if I feel brave enough to run `npm audit --fix` though, but it might be necessary

**Comment by alsmyr** [comment]
What happens if we make CI fail on audit failures and then we have to manually --fix?

**Comment by alsmyr** [comment]
I see. It a nice piece of functionality but can be hard to put into use. 

I got a hard question from a customer about a month ago:

> how to you do vendor assessment on 3rd party dependencies?

Merits some discussion that one...

**Comment by andreineculau** [comment]
closing this in the light of https://github.com/tobiipro/support-firecloud/issues/121 but also articles like https://www.nearform.com/blog/comparing-npm-audit-with-snyk/

recommendation: use specific services that do one thing well
