### ISSUE TITLE
implement cloudformation drift checks

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/support-firecloud#56]
in repo/cfn/inc.mk

for any team environment e.g. dev staging prod
provisioning should actually fail if the stack has drifted

for all environment, after we provision, we should report if the stack shows as drifted (it can happen because we set maybe an empty array in the template, but cfn transforms that into undefined, and then reports the stack as drifted... 🤷‍♂️ )

**Comment by andreineculau** [comment]
uncertain how we should handle a drift.

ideally, we should not deploy to a group of stacks that has drifted, and we should also report that the stacks have drifted just after deployment (it shows that the template can be rewritten and avoid fake drifts like cloudformation accepting `[]` as value, but rewriting/exposing it as undefined)

but that can also simply stop you from deploying, unless you introduce some way to forcefully do it.

**Comment by alsmyr** [comment]
Is there a pattern for this that we could follow? I can send an email to Gustav from AWS and start a discussion on it.

**Comment by andreineculau** [comment]
no, no pattern. it's a new-ish thing which wasn't taken full way (that's a pattern! 😉 ): they don't have the functionality to fix the drifts. If they did, the pattern would be simply fixing the drifts before/after updating the stack. The state would then be deterministic when deploying an env.

As it is now - just checking for drifts... 🤷‍♂️ I can only do a system test where i say there should be no drifts. But with these fake drifts, there will be many false negatives.

**Comment by IanSavchenko** [comment]
I think that drifts themselves are not that bad thing - sometimes you experiment and try stuff and then want it to be cleaned with a fresh deployment, so having a hard stop before deployment would be quite annoying. 

For now: I would suggest having a drift report printed in the logs or somewhere, so we can have it. This can help to debug in some cases, I think. 

For the future: we could check for a drift right after deployment as Andrei suggested above, after a couple of runs we can clear out all those cases where drifts are created. Also, if we add a CFN linter, we could check for those cases preemptively.

**Comment by andreineculau** [comment]
I find it "super bad" to have drifts related to prod and staging envs. And then just "not nice" related to dev and git-master. All the other envs, 🤷‍♂️ should adhere to "knock yourself out".

> For now: I would suggest having a drift report printed in the logs or somewhere, so we can have it. This can help to debug in some cases, I think.

in place, but with the code folding and so on, you really need to look for them. Instead one can go int the cloudformation UI and check the drift column (updated every time we deploy, since we trigger a drift check).

**Comment by IanSavchenko** [comment]
> I find it "super bad" to have drifts related to prod and staging envs. And then just "not nice" related to dev and git-master. All the other envs, 🤷‍♂️ should adhere to "knock yourself out".

It's bad, but it is a reality sometimes, that we need to go and patch prod until a proper deployment rolls out. And if we will be blocking deployment just because there is a drift, it will make our "sensitive" deployments even more like that. So unless we have some kind of confirmation step "We have detected a drift. Want to proceed? (Y/n)", I wouldn't want it the check to run in a blocking mode on the "before" step.

> in place, but with the code folding and so on, you really need to look for them. Instead one can go int the cloudformation UI and check the drift column (updated every time we deploy, since we trigger a drift check).

Cool! 👏  I don't open too often either of them (Travis probably is faster to look at), but we can push a slack notification when drift is detected after deployment.

**Comment by andreineculau** [comment]
> we need to go and patch prod until a proper deployment rolls out. And if we will be blocking deployment just because there is a drift

I know. I wasn't clear in my previous message about my preference to check (and fix, if they implement a fix functionality) drifts AFTER deployment, so as to let the deployment finish. Being OCD about these things can lead to a worse situation that you have without any checks at all.

> but we can push a slack notification when drift is detected after deployment.

glad to have you back, and thinking alike :) i think we still have the "send slack message" script in the bin folder, so it's a matter of exposing the slack webhook as a travis encrypted var
