### ISSUE TITLE
`make release` for tagged releases nukes and rebuilds everything 

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/support-firecloud#83]
This should only happen for npm-publish-git.

**Comment by andreineculau** [comment]
My bad. OCD kicked in, i realized the mistake but i guess i forgot to commit and push the correction. 😕

**Comment by IanSavchenko** [comment]
not a big deal, it will wait for you to fix it :)

**Comment by andreineculau** [comment]
fixed in 07fc002
I knew I don't know what I'm doing, so I had an atomic commit just for this change 😉
