### ISSUE TITLE
add make targets for regular transcrypt usage

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/support-firecloud#92]
e.g.

```
make crypt # init repo with transcrypt or if already done, then encrypt
make crypt/allow # allow someone to decrypt
make crypt/disallow # disallow someone to decrypt
make decrypt # init repo with transcrypt or if already done, then decrypt
```

feedback welcome @jobackman 

NOTE: update docs with new commands https://github.com/tobiipro/support-firecloud/blob/master/doc/how-to-manage-secrets.md

**Comment by andreineculau** [comment]
thought about it, but it involves touching the .gitattributes file automagically and... that's maybe not a good idea

now that i think about it, probably the only target that is really needed is `make decrypt` because that's what a few will use a few times. but initializing, add a new encrypted file, or flushing the credentials will happen close to once a year and then it's better to read the docs :)

**Comment by jobackman** [comment]
> thought about it, but it involves touching the .gitattributes file automagically and... that's maybe not a good idea

Ah, yeah you're probably right, lets skip that then.

> now that i think about it, probably the only target that is really needed is make decrypt because that's what a few will use a few times. 

Agreed, this is where the gold lies 🏅
